rules:
  body-leading-blank:
    - 1
    - always
  body-max-line-length:
    - 2
    - always
    - 96
  footer-leading-blank:
    - 1
    - always
  footer-max-line-length:
    - 2
    - always
    - 96
  header-max-length:
    - 2
    - always
    - 72 # github hides text beyond this length behind an ellipsis
  subject-case:
    - 2
    - always
    - - lower-case
      - kebab-case
      - snake-case
  subject-empty:
    - 2
    - never
  subject-full-stop:
    - 2
    - never
    - .
  type-empty:
    - 2
    - never
  type-enum:
    - 2
    - always
    - - M # Major          => Incompatible change
      - m # Minor          => Backward compatible feature
      - p # Patch          => Backward compatible bug fix
      - r # Refactor       => Backward compatible improvement
      - x # Miscellaneous  => Neutral change (documentation, ci/cd, dev dependencies, etc.)
