#!/bin/sh

. "$KANO_HELPERS/colorize"
. "$KANO_HELPERS/report"

press_enter_to_continue() {
  MESSAGE="${1-"Press ENTER to continue"}"

  report message "$(colorize "$MESSAGE" bold_white)"
  _read_enter
}

_read_enter() {
  read -r _
  unset _
}
