#!/bin/sh

. "$SOURCE_DIRECTORY/builtin/helpers/colorize"

report() {
  message() {
    MESSAGE="$1"
    COLOR="$2"

    if [ -n "$COLOR" ]; then
      printf "%s\n" "$(colorize "$MESSAGE" "$COLOR")"
    else
      printf "%s\n" "$MESSAGE"
    fi
  }

  success() {
    MESSAGE="$1"

    message "$MESSAGE" green
  }

  info() {
    MESSAGE="$1"

    message "$MESSAGE" cyan
  }

  warning() {
    MESSAGE="$1"

    message "$MESSAGE" yellow
  }

  error() {
    MESSAGE="$1"

    message "$MESSAGE" red >&2
  }

  "$@"
}
