#!/bin/sh

export BUILD_DIRECTORY="$PWD/build"
export RELEASE_DIRECTORY="$PWD/kano"
export SOURCE_DIRECTORY="$PWD/sources"
export TEST_DIRECTORY="$PWD/tests"
export TEST_COVERAGE_DIRECTORY="$PWD/coverage"
