#!/bin/sh

export KANO_DEVELOPMENT_IMAGE="ghcr.io/logisparte/kano-dev"
export BUILD_DIRECTORY="$PWD/build"
export RELEASE_DIRECTORY="$PWD/release"
export SOURCE_DIRECTORY="$PWD/sources"
export TEST_DIRECTORY="$PWD/tests"
export TEST_COVERAGE_DIRECTORY="$PWD/coverage"
