#!/bin/sh -e

. "$SHELL_HELPERS/find_this_directory"

kano() {
  KANO_SOURCE_DIRECTORY="$(find_this_directory)"
  export KANO_SOURCE_DIRECTORY
  export KANO_BUILTIN_DIRECTORY="$KANO_SOURCE_DIRECTORY/builtin"
  export KANO_GLOBAL_DIRECTORY="$HOME/.kano_global"
  export KANO_LOCAL_DIRECTORY="$PWD/.kano"

  . "$KANO_SOURCE_DIRECTORY/task_router"
  task_router route_task "$@"
}

kano "$@"
