#!/bin/sh -e

kano() {
  if [ -h "$0" ]; then
    KANO_EXECUTABLE="$(readlink "$0")"

  else
    KANO_EXECUTABLE="$0"
  fi

  KANO_ROOT_DIRECTORY="$(dirname "$KANO_EXECUTABLE")"
  export KANO_ROOT_DIRECTORY

  # Deprecated, use $KANO_ROOT_DIRECTORY
  export KANO_SOURCE_DIRECTORY="$KANO_ROOT_DIRECTORY"

  # Deprecated, not intended as public variable, will be removed
  export KANO_BUILTIN_DIRECTORY="$KANO_ROOT_DIRECTORY/builtin"

  export KANO_HELPERS="$KANO_ROOT_DIRECTORY/builtin/helpers"
  export KANO_SYSTEM_DIRECTORY="/etc/kano"
  export KANO_TEAMS_DIRECTORY="$HOME/.kano_teams"
  export KANO_USER_DIRECTORY="$HOME/.kano_user"
  export KANO_PROJECT_DIRECTORY="$PWD/.kano"
  KANO_PROJECT_NAME="$(basename "$PWD")"
  export KANO_PROJECT_NAME

  . "$KANO_ROOT_DIRECTORY/router"
  router route "$@"
}

kano "$@"
