#!/bin/sh

. "$SHELL_HELPERS/does_directory_exist"
. "$SHELL_HELPERS/does_file_exist"
. "$SHELL_HELPERS/does_symbol_exist"
. "$SHELL_HELPERS/fail"

router() {
  route() {
    TASK="$1"
    shift

    TASK_FILE_PATH="$KANO_LOCAL_TASK_DIRECTORY/$TASK"
    if ! does_directory_exist "$KANO_LOCAL_DIRECTORY"; then
      fail "No local kano directory found at '$KANO_LOCAL_DIRECTORY'"

    elif ! does_file_exist "$TASK_FILE_PATH"; then
      fail "No local task named '$TASK'"

    else
      if does_file_exist "$KANO_LOCAL_ENVIRONMENT_FILE"; then
        _import "$KANO_LOCAL_ENVIRONMENT_FILE"
      fi

      _import "$TASK_FILE_PATH"

      if ! does_symbol_exist "$TASK"; then
        fail "Local task '$TASK' was not properly defined in '$TASK_FILE_PATH'"
      fi

      "$TASK" "$@"
    fi
  }

  "$@"
}

_import() {
  . "$1"
}
