#!/bin/sh

. "$SOURCE_DIRECTORY/builtin/helpers/does_directory_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/does_file_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/fail"
. "$SOURCE_DIRECTORY/scope_mapper"

scope_walker() {
  walk_up() {
    for SCOPE in $(scope_mapper list_all_scopes_in_order); do
      SCOPE_DIRECTORY="$(scope_mapper map_directory_from_name "$SCOPE")"
      if does_directory_exist "$SCOPE_DIRECTORY"; then
        echo "$SCOPE"
      fi
    done
  }

  walk_down() {
    STOP_AT_SCOPE="$1"

    for SCOPE in $(scope_mapper list_all_scopes_in_reverse); do
      SCOPE_DIRECTORY="$(scope_mapper map_directory_from_name "$SCOPE")"
      if does_directory_exist "$SCOPE_DIRECTORY"; then
        echo "$SCOPE"
      fi

      if [ -n "$STOP_AT_SCOPE" ] && [ "$SCOPE" = "$STOP_AT_SCOPE" ]; then
        return
      fi
    done
  }

  "$@"
}
