#!/bin/sh

. "$SOURCE_DIRECTORY/builtin/helpers/does_file_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/does_symbol_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/fail"
. "$SOURCE_DIRECTORY/scope_mapper"
. "$SOURCE_DIRECTORY/scope_walker"

task_executor() {
  execute_task() {
    SCOPE_DIRECTORY="$1"
    TASK="$2"
    shift 2

    for WALKED_SCOPE in $(scope_walker walk_down "$SCOPE_DIRECTORY"); do
      WALKED_SCOPE_DIRECTORY="$(scope_mapper map_directory_from_name "$WALKED_SCOPE")"
      if does_file_exist "$WALKED_SCOPE_DIRECTORY/environment"; then
        _import "$WALKED_SCOPE_DIRECTORY/environment"
      fi
    done

    TASK_FILE="$SCOPE_DIRECTORY/tasks/$TASK"
    _import "$TASK_FILE"

    if ! does_symbol_exist "$TASK"; then
      fail "Task '$TASK' was not properly defined in '$TASK_FILE'"
    fi

    "$TASK" "$@"
  }

  "$@"
}

_import() {
  . "$1"
}
