#!/bin/sh

. "$SOURCE_DIRECTORY/builtin/helpers/does_file_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/does_symbol_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/fail"
. "$SOURCE_DIRECTORY/scope_walker"

task_executor() {
  execute_task() {
    SCOPE_DIRECTORY="$1"
    TASK="$2"
    shift 2

    for ENVIRONMENT_FILE in $(scope_walker list_scope_environments "$SCOPE_DIRECTORY"); do
      _import "$ENVIRONMENT_FILE"
    done

    TASK_FILE="$SCOPE_DIRECTORY/tasks/$TASK"
    _import "$TASK_FILE"

    if ! does_symbol_exist "$TASK"; then
      fail "Task '$TASK' was not properly defined in '$TASK_FILE'"
    fi

    "$TASK" "$@"
  }

  "$@"
}

_import() {
  . "$1"
}
