#!/bin/sh

. "$SOURCE_DIRECTORY/builtin/helpers/does_file_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/fail"
. "$SOURCE_DIRECTORY/task_executor"

task_router() {
  route_task() {
    case "$1" in
      -*)
        FLAG="$1"
        if [ -n "$2" ]; then
          TASK="$2"
          shift 2

        else
          fail "Must provide a task name when overriding with a flag"
        fi
        ;;

      *)
        FLAG=""
        if [ -n "$1" ]; then
          TASK="$1"
          shift 1

        else
          TASK="help"
        fi
        ;;
    esac

    case "$FLAG" in
      -u | --user)
        if does_file_exist "$KANO_USER_DIRECTORY/tasks/$TASK"; then
          task_executor execute_task "$KANO_USER_DIRECTORY" "$TASK" "$@"

        else
          fail "No user task named '$TASK'"
        fi
        ;;

      -s | --system)
        if does_file_exist "$KANO_SYSTEM_DIRECTORY/tasks/$TASK"; then
          task_executor execute_task "$KANO_SYSTEM_DIRECTORY" "$TASK" "$@"

        else
          fail "No system task named '$TASK'"
        fi
        ;;

      -b | --builtin)
        if does_file_exist "$KANO_BUILTIN_DIRECTORY/tasks/$TASK"; then
          task_executor execute_task "$KANO_BUILTIN_DIRECTORY" "$TASK" "$@"

        else
          fail "No builtin task named '$TASK'"
        fi
        ;;

      "")
        if does_file_exist "$KANO_PROJECT_DIRECTORY/tasks/$TASK"; then
          task_executor execute_task "$KANO_PROJECT_DIRECTORY" "$TASK" "$@"

        elif does_file_exist "$KANO_USER_DIRECTORY/tasks/$TASK"; then
          task_executor execute_task "$KANO_USER_DIRECTORY" "$TASK" "$@"

        elif does_file_exist "$KANO_SYSTEM_DIRECTORY/tasks/$TASK"; then
          task_executor execute_task "$KANO_SYSTEM_DIRECTORY" "$TASK" "$@"

        elif does_file_exist "$KANO_BUILTIN_DIRECTORY/tasks/$TASK"; then
          task_executor execute_task "$KANO_BUILTIN_DIRECTORY" "$TASK" "$@"

        else
          fail "No project, user, system or builtin task named '$TASK'"
        fi
        ;;

      *)
        fail "Invalid flag '$FLAG'"
        ;;
    esac
  }

  "$@"
}
