#!/bin/sh

. "$SOURCE_DIRECTORY/builtin/helpers/does_file_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/does_symbol_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/fail"

task_executor() {
  execute_task() {
    SCOPE_DIRECTORY="$1"
    TASK="$2"
    shift 2

    ENVIRONMENT_FILE="$SCOPE_DIRECTORY/environment"
    TASK_FILE="$SCOPE_DIRECTORY/tasks/$TASK"
    if does_file_exist "$ENVIRONMENT_FILE"; then
      _import "$ENVIRONMENT_FILE"
    fi

    _import "$TASK_FILE"

    if ! does_symbol_exist "$TASK"; then
      fail "Task '$TASK' was not properly defined in '$TASK_FILE'"
    fi

    "$TASK" "$@"
  }

  "$@"
}

_import() {
  . "$1"
}
