#!/bin/sh -e

LEGACY_INSTALLATION_DIRECTORY="/usr/local/opt/kano"
INSTALLATION_DIRECTORY="/opt/kano"
EXECUTABLE_DIRECTORY="/usr/bin"
THIS_DIRECTORY="$(dirname "$0")"

install() {
  _uninstall_previous_installation_if_any
  _install_current_package
  _test_installation
}

_uninstall_previous_installation_if_any() {
  if [ -f "$LEGACY_INSTALLATION_DIRECTORY/uninstall" ]; then
    "$LEGACY_INSTALLATION_DIRECTORY/uninstall"
  fi

  if [ -f "$INSTALLATION_DIRECTORY/uninstall" ]; then
    "$INSTALLATION_DIRECTORY/uninstall"
  fi
}

_install_current_package() {
  mkdir -p "$INSTALLATION_DIRECTORY"
  cp -R "$THIS_DIRECTORY"/* "$INSTALLATION_DIRECTORY"
  ln -s "$INSTALLATION_DIRECTORY/lib/kano" "$EXECUTABLE_DIRECTORY/kano"
}

_test_installation() {
  HELP_OUTPUT="$(kano help)"
  case "$HELP_OUTPUT" in
    *"Show this help message"*)
      echo "Successfully installed kano"
    ;;

  *)
    echo "Failed to install kano"
    exit 1
    ;;
  esac
}

install "$@"
