#!/bin/sh

. "$KANO_HELPERS/find_and_replace_in_directory"
. "$KANO_HELPERS/report"

build_help() {
  echo "Build the project"
}

build() {
  _clear_directory
  _copy_source_files
  _configure_executable
}

_clear_directory() {
  _info "Clearing build directory"
  rm -rf "$BUILD_DIRECTORY"
  mkdir -p "$BUILD_DIRECTORY"
}

_copy_source_files() {
  _info "Copying source files"
  cp -r "$SOURCE_DIRECTORY"/* "$BUILD_DIRECTORY"
}

_configure_executable() {
  chmod +x "$BUILD_DIRECTORY/kano"
}

_info() {
  MESSAGE="$1"

  report info "[build] $MESSAGE"
}
