#!/bin/sh

. "$SHELL_HELPERS/does_directory_exist"
. "$SHELL_HELPERS/fail"
. "$SHELL_HELPERS/report"

coverage_help() {
  echo "View the coverage report for the last test run"
}

coverage() {
  if ! does_directory_exist "$TEST_COVERAGE_DIRECTORY"; then
    fail "No coverage report found. Run tests with coverage first"
  fi

  report info "[coverage] Opening coverage report in browser..."

  if uname -a | grep -q "Linux"; then
    xdg-open "$TEST_COVERAGE_DIRECTORY/index.html"

  elif uname -a | grep -q "Darwin"; then
    open "$TEST_COVERAGE_DIRECTORY/index.html"
  fi
}
