#!/bin/sh

. "$KANO_HELPERS/does_file_exist"
. "$KANO_HELPERS/fail"

COVERAGE_REPORT="$TEST_COVERAGE_DIRECTORY/index.html"

coverage_help() {
  echo "View the coverage report for the last test run"
}

coverage() {
  if ! does_file_exist "$COVERAGE_REPORT"; then
    fail "No coverage report found. Run tests with coverage first"
  fi

  echo "file://$COVERAGE_REPORT"
}
