#!/bin/sh

. "$KANO_HELPERS/git/get_all_files"
. "$KANO_HELPERS/git/get_dirty_files"
. "$KANO_HELPERS/report"

format_help() {
  echo "Format the project to ensure visual consistency"
}

format() {
  FILTER="$1"

  case "$FILTER" in
    dirty | "")
      FILTERED_FILES="$(get_dirty_files)"
      ;;

    all)
      FILTERED_FILES="$(get_all_files)"
      ;;

    *)
      fail "Unknown filter: $FILTER"
      ;;
  esac

  _format_shell "$FILTERED_FILES"
  _format_markdown_and_yaml "$FILTERED_FILES"
}

_format_shell() {
  FILES="$1"

  SHELL_FILES="$(echo "$FILES" | grep "\.kano\|sources" | grep -v "Dockerfile" || true)"
  if [ -z "$SHELL_FILES" ]; then
    return
  fi

  _info "Formatting shell files"
  report message "$SHELL_FILES" "gray"
  echo "$SHELL_FILES" | xargs shfmt -p -w -bn -ci -sr -kp -i 2
}

_format_markdown_and_yaml() {
  FILES="$1"

  MARKDOWN_YAML_FILES="$(echo "$FILES" | grep -e "\.md$\|.yml$\|.yaml$" || true)"
  if [ -z "$MARKDOWN_YAML_FILES" ]; then
    return
  fi

  _info "Formatting markdown and yaml files"
  echo "$MARKDOWN_YAML_FILES" | xargs prettier --write
}

_info() {
  MESSAGE="$1"

  report info "[format] $MESSAGE"
}
