#!/bin/sh

. "$KANO_HELPERS/report"

format_help() {
  echo "Format the project to ensure visual consistency"
}

format() {
  _format_shell
  _format_markdown_and_yaml
}

_format_shell() {
  _info "Formatting shell files"
  shfmt -p -w -bn -ci -sr -i 2 .kano sources tests templates
}

_format_markdown_and_yaml() {
  _info "Formatting markdown and yaml files"
  prettier --write .github docs
}

_info() {
  MESSAGE="$1"

  report info "[format] $MESSAGE"
}
