#!/bin/sh

. "$SHELL_HELPERS/report"

format_help() {
  echo "Format the project to ensure visual consistency"
}

format() {
  _format_shell && _format_markdown_and_yaml
  return $?
}

_format_shell() {
  _info "Formatting shell files"
  shfmt -p -w -bn -ci -sr -kp -i 2 .kano sources tests
  return $?
}

_format_markdown_and_yaml() {
  _info "Formatting markdown and yaml files"
  prettier --write .github docs
  return $?
}

_info() {
  MESSAGE="$1"

  report info "[format] $MESSAGE"
}
