#!/bin/sh

. "$KANO_HELPERS/report"

lint_help() {
  echo "Lint the project to ensure the code follows best practices"
}

lint() {
  _lint_shell
  _lint_markdown
}

_lint_shell() {
  _info "Linting shell files"
  find "$SOURCE_DIRECTORY" -type f -exec shellcheck {} +
}

_lint_markdown() {
  _info "Linting markdown files"
  markdownlint '**/*.md'
}

_info() {
  MESSAGE="$1"

  report info "[lint] $MESSAGE"
}
