#!/bin/sh

. "$SHELL_HELPERS/report"

setup_help() {
  echo "Install git hooks"
}

setup() {
  _install_git_hooks
}

_install_git_hooks() {
  report info "[setup] Installing git hooks"
  GIT_DIRECTORY="$(git rev-parse --git-dir)"
  GIT_HOOK_DIRECTORY="$GIT_DIRECTORY/hooks"
  cp -r "$KANO_LOCAL_GIT_HOOK_DIRECTORY"/* "$GIT_HOOK_DIRECTORY"
}
