#!/bin/sh

. "$KANO_HELPERS/report"

setup_help() {
  echo "Install git hooks and build docker image"
}

setup() {
  _install_git_hooks
  _build_docker_image
}

_install_git_hooks() {
  report info "[setup] Installing git hooks"
  GIT_DIRECTORY="$(git rev-parse --git-dir)"
  cat > "$GIT_DIRECTORY/hooks/pre-commit" << EOF
#!/bin/sh -e

kano pre_commit
EOF
}

_build_docker_image() {
  docker build --tag "kano:local" --cache-from "kano:local" .
}
