#!/bin/sh

. "$KANO_HELPERS/report"

setup_help() {
  echo "Build the development Docker image and install the git hooks"
}

setup() {
  _build_development_image
  _install_git_hooks
}

_build_development_image() {
  _info "Building development image"
  kano docker build
}

_install_git_hooks() {
  _info "Installing git hooks"
  git config --local core.hooksPath "$KANO_PROJECT_DIRECTORY/hooks"
}

_info() {
  MESSAGE="$1"

  report info "[setup] $MESSAGE"
}
