#!/bin/sh

. "$KANO_HELPERS/report"

teardown_help() {
  echo "Uninstall git hooks (inverse of setup)"
}

teardown() {
  _uninstall_git_hooks
}

_uninstall_git_hooks() {
  report info "[teardown] Uninstalling git hooks"
  git config --local --unset core.hooksPath
}
