#!/bin/sh

. "$SHELL_HELPERS/report"

teardown_help() {
  echo "Uninstall git hooks (inverse of setup)"
}

teardown() {
  _uninstall_git_hooks
}

_uninstall_git_hooks() {
  report info "[teardown] Uninstalling git hooks"
  GIT_DIRECTORY="$(git rev-parse --git-dir)"
  GIT_HOOK_DIRECTORY="$GIT_DIRECTORY/hooks"
  rm -rf "$GIT_HOOK_DIRECTORY"
  mkdir "$GIT_HOOK_DIRECTORY"
}
