#!/bin/sh

. "$KANO_HELPERS/does_directory_exist"
. "$KANO_HELPERS/fail"
. "$KANO_HELPERS/report"

TEST_SUITE_DIRECTORY="$TEST_DIRECTORY/suites"

test_help() {
  echo "Test the project to ensure the code behaves as intended"
}

test() {
  SUITE_NAME="$1"

  if [ -z "$SUITE_NAME" ]; then
    _info "Running all tests"
    _test "$TEST_SUITE_DIRECTORY"

  elif does_directory_exist "$TEST_SUITE_DIRECTORY/$SUITE_NAME"; then
    _info "Running $SUITE_NAME tests"
    _test "$TEST_SUITE_DIRECTORY/$SUITE_NAME"

  else
    fail "[test] No test suite named '$SUITE_NAME'"
  fi
}

_test() {
  SUITE_PATH="$1"

  # Ensure that the kano code under test is the one in the source directory
  INITIAL_KANO_SYSTEM_DIRECTORY="$KANO_SYSTEM_DIRECTORY"
  INITIAL_KANO_TEAMS_DIRECTORY="$KANO_TEAMS_DIRECTORY"
  INITIAL_KANO_USER_DIRECTORY="$KANO_USER_DIRECTORY"
  INITIAL_KANO_PROJECT_DIRECTORY="$KANO_PROJECT_DIRECTORY"
  INITIAL_KANO_PROJECT_NAME="$KANO_PROJECT_NAME"
  INITIAL_KANO_TEAM="$KANO_TEAM"

  export KANO_SYSTEM_DIRECTORY="$TEST_DIRECTORY/data/some_system/kano"
  export KANO_TEAMS_DIRECTORY="$TEST_DIRECTORY/data/some_home/.kano_teams"
  export KANO_USER_DIRECTORY="$TEST_DIRECTORY/data/some_home/.kano_user"
  export KANO_PROJECT_DIRECTORY="$TEST_DIRECTORY/data/some_project/.kano"
  export KANO_PROJECT_NAME="some_project"
  unset KANO_TEAM

  # bash shell is required because of
  # [kcov limitation](https://github.com/SimonKagstrom/kcov/issues/137)
  shellspec \
    --shell bash \
    --default-path "$SUITE_PATH" \
    --pattern "*.test" \
    --kcov \
    --kcov-options="\
      --exclude-pattern=$SOURCE_DIRECTORY/kano \
      --include-pattern=$SOURCE_DIRECTORY/" \
    --covdir "$TEST_COVERAGE_DIRECTORY"
  RESULT=$?

  # Reset environment
  export KANO_SYSTEM_DIRECTORY="$INITIAL_KANO_SYSTEM_DIRECTORY"
  export KANO_TEAMS_DIRECTORY="$INITIAL_KANO_TEAMS_DIRECTORY"
  export KANO_USER_DIRECTORY="$INITIAL_KANO_USER_DIRECTORY"
  export KANO_PROJECT_DIRECTORY="$INITIAL_KANO_PROJECT_DIRECTORY"
  export KANO_PROJECT_NAME="$INITIAL_KANO_PROJECT_NAME"
  export KANO_TEAM="$INITIAL_KANO_TEAM"

  return $RESULT
}

_info() {
  MESSAGE="$1"

  report info "[test] $MESSAGE"
}
