#!/bin/sh

. "$KANO_HELPERS/does_directory_exist"
. "$KANO_HELPERS/does_symbol_exist"
. "$KANO_HELPERS/fail"
. "$KANO_HELPERS/report"

TEST_SUITE_DIRECTORY="$TEST_DIRECTORY/suites"

test_help() {
  echo "Test the project to ensure the code behaves as intended"
}

test() {
  SUITE_NAME="$1"

  if [ -n "$SUITE_NAME" ]; then
    SUITE_PATH="$TEST_SUITE_DIRECTORY/$SUITE_NAME"
    if does_directory_exist "$SUITE_PATH"; then
      _info "Running $SUITE_NAME tests"
      _test "$SUITE_PATH"
      return $?

    else
      fail "[test] No test suite named '$SUITE_NAME'"
    fi

  else
    SUITE_PATH="$TEST_SUITE_DIRECTORY"
    _info "Running all tests"
    _test "$SUITE_PATH"
    return $?
  fi
}

_test() {
  SUITE_PATH="$1"

  # Ensure that the kano code under test is the one in the source directory
  INITIAL_KANO_SOURCE_DIRECTORY="$KANO_SOURCE_DIRECTORY"
  INITIAL_KANO_BUILTIN_DIRECTORY="$KANO_BUILTIN_DIRECTORY"
  INITIAL_KANO_GLOBAL_DIRECTORY="$KANO_GLOBAL_DIRECTORY"
  INITIAL_KANO_LOCAL_DIRECTORY="$KANO_LOCAL_DIRECTORY"

  export KANO_SOURCE_DIRECTORY="$"
  export KANO_BUILTIN_DIRECTORY="$SOURCE_DIRECTORY/builtin"
  export KANO_GLOBAL_DIRECTORY="$TEST_DIRECTORY/data/some_home/.kano_global"
  export KANO_LOCAL_DIRECTORY="$TEST_DIRECTORY/data/some_project/.kano"

  shellspec \
    --default-path "$SUITE_PATH" \
    --pattern "*.test" \
    --kcov \
    --kcov-options="\
      --exclude-pattern=/$SOURCE_DIRECTORY/kano \
      --include-pattern=/$SOURCE_DIRECTORY/"
  RESULT=$?

  # Reset environment
  export KANO_SOURCE_DIRECTORY="$INITIAL_KANO_SOURCE_DIRECTORY"
  export KANO_BUILTIN_DIRECTORY="$INITIAL_KANO_BUILTIN_DIRECTORY"
  export KANO_GLOBAL_DIRECTORY="$INITIAL_KANO_GLOBAL_DIRECTORY"
  export KANO_LOCAL_DIRECTORY="$INITIAL_KANO_LOCAL_DIRECTORY"

  return $RESULT
}

_info() {
  MESSAGE="$1"

  report info "[test] $MESSAGE"
}
