#!/bin/sh

file_system_interactor() {
  load_configuration_file() {
    FILE_PATH="$1"

    . "$FILE_PATH"
  }

  read_variable_from_configuration_file() {
    VARIABLE_NAME="$1"
    FILE_PATH="$2"

    grep "$VARIABLE_NAME" "$FILE_PATH" | cut -d "\"" -f 2
  }

  "$@"
}
