#!/bin/sh

dockered_help() {
  echo "Run a kano task in a docker container"
}

dockered() {
  if [ "$KANO_DOCKER" = true ]; then
    _kano "$@"

  else
    _kano docker execute kano "$@"
  fi
}

_kano() {
  command kano "$@"
}
