#!/bin/sh

. "$KANO_SOURCE_DIRECTORY/builtin/helpers/does_directory_exist"
. "$KANO_SOURCE_DIRECTORY/builtin/helpers/does_file_exist"
. "$KANO_SOURCE_DIRECTORY/builtin/helpers/fail"

SYSTEM_DOCKER="$(command -v docker)"
DEVELOPMENT_IMAGE="kano_${KANO_PROJECT_NAME}:local"

docker_help() {
  echo "Run project tasks inside a Docker container"
}

docker() {
  if ! _is_docker_installed; then
    fail "Docker is not installed"
  fi

  if ! does_directory_exist "$KANO_PROJECT_DIRECTORY"; then
    fail "No kano directory exists in project"
  fi

  if ! does_file_exist "$KANO_PROJECT_DIRECTORY/Dockerfile"; then
    fail "No Dockerfile in project kano directory"
  fi

  build() {
    if _does_development_image_exist; then
      _docker_build --cache-from "$DEVELOPMENT_IMAGE" "$@"

    else
      _docker_build "$@"
    fi
  }

  "$@"
}

_docker_build() {
  _docker build \
    --file "$KANO_PROJECT_DIRECTORY/Dockerfile" \
    --tag "$DEVELOPMENT_IMAGE" \
    "$@" .
}

_does_development_image_exist() {
  _docker image inspect "$DEVELOPMENT_IMAGE" > /dev/null 2>&1
  return $?
}

_is_docker_installed() {
  [ -n "$SYSTEM_DOCKER" ]
  return $?
}

_docker() {
  "$SYSTEM_DOCKER" "$@"
}
