#!/bin/sh

. "$SOURCE_DIRECTORY/builtin/helpers/am_i_root"
. "$SOURCE_DIRECTORY/builtin/helpers/does_directory_exist"
. "$SOURCE_DIRECTORY/builtin/helpers/fail"
. "$SOURCE_DIRECTORY/builtin/helpers/report"

init_help() {
  echo "Initialize tasks and/or kano directories"
}

init() {
  SCOPE="$1"
  TEMPLATE="$2"

  case "$SCOPE" in
    "")
      SCOPE="project"
      ;;

    project | user)
      shift
      ;;

    system)
      if ! am_i_root; then
        fail "System tasks or directories can only be initialized by root user." \
          "Re-run with sudo"

      else
        shift
      fi
      ;;

    task)
      _initialize_template project task "$2"
      return $?
      ;;

    *)
      fail "Unknown scope '$SCOPE'. Must be either 'project', 'user' or 'system'"
      ;;
  esac

  case "$TEMPLATE" in
    "")
      TEMPLATE="directory"
      ;;

    directory | task)
      shift
      ;;

    *)
      fail "Unknown template '$TEMPLATE'. Must be either 'directory' or 'task'"
      ;;
  esac

  _initialize_template "$SCOPE" "$TEMPLATE" "$@"
}

_initialize_template() {
  SCOPE="$1"
  TEMPLATE="$2"

  if [ "$SCOPE" = "project" ]; then
    SCOPE_DIRECTORY="$KANO_PROJECT_DIRECTORY"

  elif [ "$SCOPE" = "user" ]; then
    SCOPE_DIRECTORY="$KANO_USER_DIRECTORY"

  elif [ "$SCOPE" = "system" ]; then
    SCOPE_DIRECTORY="$KANO_SYSTEM_DIRECTORY"

  else
    fail
  fi

  if [ "$TEMPLATE" = "directory" ]; then
    _initialize_directory "$SCOPE" "$SCOPE_DIRECTORY"

  elif [ "$TEMPLATE" = "task" ]; then
    TASK="$3"
    _initialize_task "$SCOPE" "$SCOPE_DIRECTORY" "$TASK"
  fi
}

_initialize_directory() {
  SCOPE="$1"
  SCOPE_DIRECTORY="$2"

  if does_directory_exist "$SCOPE_DIRECTORY"; then
    fail "A kano directory already exists in scope '$SCOPE'"
  fi

  _create_directory "$SCOPE_DIRECTORY"
  report success "Initialized directory at: $SCOPE_DIRECTORY"
}

_initialize_task() {
  SCOPE="$1"
  SCOPE_DIRECTORY="$2"
  TASK="$3"

  if [ -z "$TASK" ]; then
    fail "No task name provided"
  fi

  if ! does_directory_exist "$SCOPE_DIRECTORY"; then
    _create_directory "$SCOPE_DIRECTORY"
  fi

  TASK_PATH="$SCOPE_DIRECTORY/tasks/$TASK"
  _create_task "$TASK_PATH"
  report success "Initialized task at: $TASK_PATH"
}

_create_directory() {
  DIRECTORY="$1"

  mkdir -p "$DIRECTORY"
  mkdir -p "$DIRECTORY/tasks"
}

_create_task() {
  TASK_PATH="$1"

  cat > "$TASK_PATH" << EOF
#!/bin/sh

${TASK}_help() {
  echo "$TASK's help description"
}

$TASK() {
  # Task code goes here
  true
}
EOF
}
