#!/bin/sh -e

install_go() {
  TARGETARCH="$1"

  VERSION="1.18.3"
  case "$TARGETARCH" in
    amd64)
      PACKAGE_ARCHITECTURE="amd64"
      ;;

    arm64*)
      PACKAGE_ARCHITECTURE="arm64"
      ;;

    *)
      echo "Unknown target architecture: $TARGETARCH" >&2
      exit 1
      ;;
  esac

  curl -L "https://golang.org/dl/go$VERSION.linux-$PACKAGE_ARCHITECTURE.tar.gz" \
    | tar -C /usr/local -xz
}

install_go "$@"
