name: CD

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  HELOT_GITHUB_USERNAME: ${{ secrets.HELOT_GITHUB_USERNAME }}
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  HELOT_GIT_EMAIL: ${{ secrets.HELOT_GIT_EMAIL }}
  REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}
  REGISTRY_URL: ghcr.io

jobs:
  build_dev_image:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      dev_image: ${{ steps.image_name.outputs.dev_image }}
    steps:
      - uses: actions/checkout@v2
        name: Clone

      - name: Extract version
        id: version
        run: |
          VERSION="$(echo "$GITHUB_REF" | cut -d "/" -f 3)"
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "::set-output name=version::$VERSION"

      - name: Compose development image name
        id: image_name
        run: |
          DEV_IMAGE="$REGISTRY_URL/$REPOSITORY-dev:$VERSION"
          echo "DEV_IMAGE=$DEV_IMAGE" >> "$GITHUB_ENV"
          echo "::set-output name=dev_image::$DEV_IMAGE"

      - name: Login to registry
        run: |
          echo "$HELOT_GITHUB_ACCESS_TOKEN" \
            | docker login "$REGISTRY_URL" --username "$HELOT_GITHUB_USERNAME" --password-stdin

      - name: Pull existing development image, if any
        run: docker pull "$DEV_IMAGE" || true

      - name: Build development image
        run: docker build --tag "$DEV_IMAGE" --cache-from "$DEV_IMAGE" .

      - name: Push development image
        run: docker push "$DEV_IMAGE"

  run_cd:
    runs-on: ubuntu-latest
    needs: build_dev_image
    container:
      image: ${{ needs.build_dev_image.outputs.dev_image }}
      env:
        VERSION: ${{ needs.build_dev_image.outputs.version }}
      credentials:
        username: ${{ env.HELOT_GITHUB_USERNAME }}
        password: ${{ env.HELOT_GITHUB_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        name: Clone

      - name: Build
        run: |
          export KANO_SOURCE_DIRECTORY="sources"
          export KANO_BUILTIN_DIRECTORY="$KANO_SOURCE_DIRECTORY/builtin"
          export KANO_LOCAL_DIRECTORY="$PWD/.kano"
          export KANO_HELPERS="$KANO_BUILTIN_DIRECTORY/helpers"
          . .kano/environment
          . .kano/tasks/build
          build

      - name: Release
        run: |
          export KANO_SOURCE_DIRECTORY="sources"
          export KANO_BUILTIN_DIRECTORY="$KANO_SOURCE_DIRECTORY/builtin"
          export KANO_LOCAL_DIRECTORY="$PWD/.kano"
          export KANO_HELPERS="$KANO_BUILTIN_DIRECTORY/helpers"
          . .kano/environment
          . .kano/tasks/release
          release "$VERSION"
