name: cd

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  KANO_DOCKER_TAG: ${{ github.sha }}
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_BUILDKIT: true

permissions:
  contents: write # Required for release
  packages: write # Required for release and docker

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/5.0.1/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Pull existing development image
        run: kano docker image pull

      - name: Build project
        run: kano dockered build

      - name: Create release token
        uses: actions/create-github-app-token@v1
        id: release-token
        with:
          app-id: ${{ secrets.HELOT_CLIENT_ID }}
          private-key: ${{ secrets.HELOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: homebrew-packages

      - name: Release project
        run: |
          kano dockered release ${{ github.ref_name }} ${{ steps.release-token.outputs.token }}

      - name: Tag versioned image
        run: |
          kano docker image tag ${{ github.ref_name }}
          kano docker image push ${{ github.ref_name }}
