name: CD

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY_URL: ghcr.io
  HELOT_GIT_NAME: helot
  HELOT_GIT_EMAIL: logisparte-helot@users.noreply.github.com
  HELOT_GITHUB_USERNAME: logisparte-helot
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  run_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl -L https://github.com/logisparte/kano/releases/download/3.0.0/kano.tar.gz \
            | tar -xz
          sudo ./kano/install

      - uses: actions/checkout@v2
        name: Clone project

      - name: Build development image
        run: kano docker build

      - name: Build project
        run: kano docker run kano build

      - name: Release project
        run: |
          VERSION="$(echo "$GITHUB_REF" | cut -d "/" -f 3)"
          kano docker run kano configure_github \
            "$HELOT_GIT_NAME" \
            "$HELOT_GIT_EMAIL" \
            "$HELOT_GITHUB_ACCESS_TOKEN"
          kano docker run --env CI="$CI" kano release "$VERSION"
