name: cd

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  DOCKER_BUILDKIT: true
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: logisparte-helot
  DOCKER_PASSWORD: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  GIT_NAME: helot
  GIT_EMAIL: logisparte-helot@users.noreply.github.com
  RELEASE_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/beta-docker-v4/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Export environment variable
        run: echo "KANO_DOCKER_IMAGE=$DOCKER_REGISTRY/$GITHUB_REPOSITORY-dev" >> "$GITHUB_ENV"

      - name: Clone project
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Pull existing development image
        run: kano docker pull "$GITHUB_SHA"

      - name: Build project
        run: kano dockered build

      - name: Release project
        run: |
          kano dockered release \
            "$GITHUB_REF_NAME" \
            "$GIT_NAME" \
            "$GIT_EMAIL" \
            "$RELEASE_GITHUB_ACCESS_TOKEN"

      - name: Tag versioned image
        run: |
          kano docker tag "$GITHUB_REF_NAME"
          kano docker push "$GITHUB_REF_NAME"
