name: cd

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

env:
  KANO_DOCKER_TAG: ${{ github.sha }}
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_BUILDKIT: true

permissions:
  contents: read # Required by actions/checkout
  packages: write # Required for release and docker

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/5.0.1/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull existing development image
        run: kano docker image pull

      - name: Build project
        run: kano dockered build

      - name: Release project
        run: kano dockered release "$GITHUB_REF_NAME" "$GITHUB_TOKEN"

      - name: Tag versioned image
        run: |
          kano docker image tag "$GITHUB_REF_NAME"
          kano docker image push "$GITHUB_REF_NAME"
