name: CD

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  cd:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/logisparte/docker-images/helot:latest
      credentials:
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GIT_TOKEN }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.HELOT_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.HELOT_AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ca-central-1
        AWS_S3_BUCKET_PACKAGE_REPOSITORY: packages.logisparte
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_NAME: ${{ secrets.GIT_NAME }}
    steps:
      - uses: actions/checkout@v2
        name: Clone

      - name: Install dependencies
        run: brew bundle install

      - name: Build
        run: kano build

      - name: Release
        run: kano release
