name: cd

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY_URL: ghcr.io
  HELOT_GIT_NAME: helot
  HELOT_GIT_EMAIL: logisparte-helot@users.noreply.github.com
  HELOT_GITHUB_USERNAME: logisparte-helot
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  run_cd:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl -L https://github.com/logisparte/kano/releases/download/3.0.0/kano.tar.gz \
            | tar -xz
          sudo ./kano/install

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.HELOT_GITHUB_USERNAME }}
          password: ${{ env.HELOT_GITHUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v2
        name: Clone project

      - name: Export development image name
        run: export DEVELOPMENT_IMAGE="$REGISTRY_URL/$REPOSITORY-dev"

      - name: Pull existing development image, if any
        run: docker pull "$DEVELOPMENT_IMAGE" || true

      - name: Build development image from cache
        run: kano docker build --cache-from "$DEVELOPMENT_IMAGE"

      - name: Build project
        run: kano docker run kano build

      - name: Release project
        run: |
          VERSION="$(echo "$GITHUB_REF" | cut -d "/" -f 3)"
          kano docker run kano release \
            "$VERSION" \
            "$HELOT_GIT_NAME" \
            "$HELOT_GIT_EMAIL" \
            "$HELOT_GITHUB_ACCESS_TOKEN"
