name: ci-branch

on:
  pull_request:
    branches:
      - master

env:
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_BUILDKIT: true

permissions:
  contents: write # Required for release
  packages: write # Required for release and docker

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/5.0.1/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build branch development image
        run: kano docker image build

      - name: Build project
        run: kano dockered build

      - name: Lint project
        run: kano dockered lint all

      - name: Test project
        run: kano dockered test

      - name: Create release token
        if: startsWith(github.head_ref, 'beta-')
        uses: actions/create-github-app-token@v1
        id: release-token
        with:
          app-id: ${{ vars.HELOT_APP_ID }}
          private-key: ${{ secrets.HELOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: homebrew-beta-packages

      - name: Release beta version
        if: startsWith(github.head_ref, 'beta-')
        run: |
          kano dockered release ${{ github.ref_name }} ${{ steps.release-token.outputs.token }}
