name: ci-branch

on:
  pull_request:
    branches:
      - master

env:
  REGISTRY_URL: ghcr.io
  HELOT_GITHUB_USERNAME: logisparte-helot
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  REPOSITORY: ${{ github.repository }}

jobs:
  run_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl -L https://github.com/logisparte/kano/releases/download/3.1.3/kano.tar.gz \
            | tar -xz
          sudo ./kano/install

      - name: Export environment variables
        run: |
          DEVELOPMENT_IMAGE="$REGISTRY_URL/$REPOSITORY-dev"
          echo "DEVELOPMENT_IMAGE=$DEVELOPMENT_IMAGE" >> "$GITHUB_ENV"

      - uses: actions/checkout@v2
        name: Clone project

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.HELOT_GITHUB_USERNAME }}
          password: ${{ env.HELOT_GITHUB_ACCESS_TOKEN }}

      - name: Pull existing development image, if any
        run: docker pull "$DEVELOPMENT_IMAGE" || true

      - name: Build development image from cache
        run: kano docker build --cache-from "$DEVELOPMENT_IMAGE"

      - name: Lint project
        run: kano docker run kano lint

      - name: Test project
        run: kano docker run kano test
