name: ci-branch

on:
  pull_request:
    branches:
      - master

env:
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_USERNAME: logisparte-helot
  DOCKER_PASSWORD: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  DOCKER_BUILDKIT: true
  GIT_NAME: helot
  GIT_EMAIL: logisparte-helot@users.noreply.github.com
  RELEASE_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}

jobs:
  check_branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/4.0.0/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build branch development image
        run: kano docker image build

      - name: Build project
        run: |
          echo "USER_ID=$(id -u)"
          echo "USER_NAME=$(id -un)"
          echo "HOME=$HOME"
          INITIALIZATION_SCRIPT="$(
            echo \
              "sudo useradd" \
              "--uid $USER_ID --gid sudo --no-create-home --home-dir $HOME $USER_NAME;" \
              "sudo passwd --delete $USER_NAME > /dev/null;" \
              "sudo chown -R $USER_NAME $HOME;" \
              "sh -c 'kill -STOP \$\$'"
          )"
          echo "$INITIALIZATION_SCRIPT"
          kano dockered build

      - name: Lint project
        run: kano dockered lint

      - name: Test project
        run: kano dockered test

      - name: Release beta version
        if: startsWith(github.head_ref, 'beta-')
        run: |
          kano dockered release \
            "$GITHUB_HEAD_REF" \
            "$GIT_NAME" \
            "$GIT_EMAIL" \
            "$RELEASE_GITHUB_ACCESS_TOKEN"
