name: ci-branch

on:
  pull_request:
    branches:
      - master

env:
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_BUILDKIT: true

permissions:
  contents: read # Required by actions/checkout
  packages: write # Required for beta release and docker

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/5.0.1/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build branch development image
        run: kano docker image build

      - name: Build project
        run: kano dockered build

      - name: Lint project
        run: kano dockered lint all

      - name: Test project
        run: kano dockered test

      - name: Release beta version
        if: startsWith(github.head_ref, 'beta-')
        run: kano dockered release "$GITHUB_REF_NAME" "$GITHUB_TOKEN"
