name: ci-beta-cleanup

on: delete

env:
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_USERNAME: logisparte-helot
  DOCKER_PASSWORD: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  DOCKER_BUILDKIT: true
  GIT_NAME: helot
  GIT_EMAIL: logisparte-helot@users.noreply.github.com
  RELEASE_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}

jobs:
  cleanup_beta:
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'beta-')
    runs-on: ubuntu-22.04
    env:
      BETA_NAME: ${{ github.event.ref }}
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/4.2.3/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Pull branch development image
        run: kano docker image pull

      - name: Unrelease beta version
        run: |
          kano dockered unrelease \
            "$BETA_NAME" \
            "$GIT_NAME" \
            "$GIT_EMAIL" \
            "$RELEASE_GITHUB_ACCESS_TOKEN"
