name: ci-cleanup

on: delete

env:
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_BUILDKIT: true

permissions:
  packages: write # Required for release cleanup and docker

jobs:
  cleanup-beta:
    if: github.event.ref_type == 'branch' && startsWith(github.event.ref, 'beta-')
    runs-on: ubuntu-latest
    env:
      BETA_NAME: ${{ github.event.ref }}
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/5.0.1/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Pull branch development image
        run: kano docker image pull

      - name: Unrelease beta version
        run: kano dockered unrelease "$BETA_NAME" ${{ github.token }}
