name: ci-master

on:
  push:
    branches:
      - master

env:
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_USERNAME: logisparte-helot
  DOCKER_PASSWORD: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  DOCKER_BUILDKIT: true

jobs:
  update_development_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/4.1.0/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build new development image
        run: kano docker image build

      - name: Tag new development image
        run: |
          kano docker image tag "$GITHUB_SHA"
          kano docker image push "$GITHUB_SHA"
          kano docker image push
