name: ci-master

on:
  push:
    branches:
      - master

env:
  REGISTRY_URL: ghcr.io
  HELOT_GITHUB_USERNAME: logisparte-helot
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  REPOSITORY: ${{ github.repository }}
  COMMIT: ${{ github.sha }}
  DOCKER_BUILDKIT: true

jobs:
  update_development_image:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl -L https://github.com/logisparte/kano/releases/download/3.4.0/kano.tar.gz \
            | tar -xz
          sudo ./kano/install

      - name: Export environment variables
        run: |
          DEVELOPMENT_IMAGE="$REGISTRY_URL/$REPOSITORY-dev"
          echo "DEVELOPMENT_IMAGE_COMMIT_TAG=$DEVELOPMENT_IMAGE:$COMMIT" >> "$GITHUB_ENV"
          echo "DEVELOPMENT_IMAGE_LATEST_TAG=$DEVELOPMENT_IMAGE:latest" >> "$GITHUB_ENV"
          echo "KANO_DEVELOPMENT_IMAGE=$DEVELOPMENT_IMAGE" >> "$GITHUB_ENV"

      - uses: actions/checkout@v2
        name: Clone project

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.HELOT_GITHUB_USERNAME }}
          password: ${{ env.HELOT_GITHUB_ACCESS_TOKEN }}

      - name: Pull existing development image, if any
        run: docker pull "$KANO_DEVELOPMENT_IMAGE" || true

      - name: Build new development image
        run: |
          kano docker build \
            --tag "$DEVELOPMENT_IMAGE_COMMIT_TAG" \
            --tag "$DEVELOPMENT_IMAGE_LATEST_TAG"

      - name: Push new development image
        run: |
          docker push "$DEVELOPMENT_IMAGE_COMMIT_TAG"
          docker push "$DEVELOPMENT_IMAGE_LATEST_TAG"
