name: ci-master

on:
  push:
    branches:
      - master

env:
  REGISTRY_URL: ghcr.io
  HELOT_GITHUB_USERNAME: logisparte-helot
  HELOT_GITHUB_ACCESS_TOKEN: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}
  REPOSITORY: ${{ github.repository }}

jobs:
  ci_update_development_image:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl -L https://github.com/logisparte/kano/releases/download/3.0.0/kano.tar.gz \
            | tar -xz
          sudo ./kano/install

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.HELOT_GITHUB_USERNAME }}
          password: ${{ env.HELOT_GITHUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v2
        name: Clone

      - name: Export development image name
        run: export DEVELOPMENT_IMAGE="$REGISTRY_URL/$REPOSITORY-dev"

      - name: Pull existing development image, if any
        run: docker pull "$DEVELOPMENT_IMAGE" || true

      - name: Build development image from cache
        run: |
          kano docker build \
            --tag "$DEVELOPMENT_IMAGE" \
            --cache-from "$DEVELOPMENT_IMAGE"

      - name: Push development image
        run: docker push "$DEVELOPMENT_IMAGE"
