name: ci-merge

on:
  delete

jobs:
  cleanup_branch:
    runs-on: ubuntu-22.04
    steps:
      - name: echo event
        env:
          EVENT: ${{ toJSON(github.event) }}
        run: echo "$EVENT"
