name: ci-master

on:
  push:
    branches:
      - master

env:
  KANO_DOCKER_REGISTRY: ghcr.io/logisparte
  DOCKER_BUILDKIT: true

permissions:
  contents: read # Required by actions/checkout
  packages: write # Required by docker

jobs:
  update-development-image:
    runs-on: ubuntu-latest
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/5.0.1/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Clone project
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.KANO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build new development image
        run: kano docker image build

      - name: Tag new development image
        run: |
          kano docker image tag "$GITHUB_SHA"
          kano docker image push "$GITHUB_SHA"
          kano docker image push
