name: ci-master

on:
  push:
    branches:
      - master

env:
  DOCKER_BUILDKIT: true
  DOCKER_REGISTRY: ghcr.io
  DOCKER_USERNAME: logisparte-helot
  DOCKER_PASSWORD: ${{ secrets.HELOT_GITHUB_ACCESS_TOKEN }}

jobs:
  update_development_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Install kano
        run: |
          curl --silent --show-error --location \
            https://github.com/logisparte/kano/releases/download/beta-docker-v4/kano.tar.gz \
              | tar --extract --gzip
          sudo ./kano/install

      - name: Export environment variables
        run: |
          DEVELOPMENT_IMAGE="$DOCKER_REGISTRY/$GITHUB_REPOSITORY-dev"
          echo "DEVELOPMENT_IMAGE_COMMIT_TAG=$DEVELOPMENT_IMAGE:$GITHUB_SHA" >> "$GITHUB_ENV"
          echo "DEVELOPMENT_IMAGE_LATEST_TAG=$DEVELOPMENT_IMAGE:latest" >> "$GITHUB_ENV"
          echo "KANO_DOCKER_IMAGE=$DEVELOPMENT_IMAGE" >> "$GITHUB_ENV"

      - name: Clone project
        uses: actions/checkout@v3

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build new development image
        run: |
          kano docker build \
            --pull \
            --tag "$DEVELOPMENT_IMAGE_COMMIT_TAG" \
            --tag "$DEVELOPMENT_IMAGE_LATEST_TAG"

      - name: Push new development image
        run: |
          docker push "$DEVELOPMENT_IMAGE_COMMIT_TAG"
          docker push "$DEVELOPMENT_IMAGE_LATEST_TAG"
