name: CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker.pkg.github.com/logisparte/docker-images/helot:latest
      credentials:
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        name: Clone

      - name: Install dependencies
        run: brew bundle install

      - name: Lint
        run: kano lint

      - name: Test
        run: kano test
